### ISSUE TITLE
Downloaded everything but crashes my arcpro

### ISSUE THREAD

**Issue by hmd2380** [Esri/deep-learning-frameworks#46] opened 2022-03-22 03:39 UTC
I am looking to use the deep learning package for building footprints so I downloaded this framework as well, as instructed. I followed each step correctly but now when I go to run the package and load it into "detect objects using deep learning" it completely crashes my arcpro. I don't even have an option to report it. Any ideas why this is happening?

**Comment by cleebp** [comment] 2022-03-25 22:00
Sorry to hear that, could you provide more information about your system like what version of arcgis pro you have installed?

**Comment by scdub** [comment] 2022-05-06 19:15
@hmd2380 If you're still having issues, can you provide some information as @cleebp had requested, or let us know if you've been able to address this problem already? Thanks!

**Comment by cleebp** [comment] 2022-06-27 17:29
Closing as non-repo, @hmd2380 if you can provide any steps or further information we can take a look.

**Closed by cleebp** 2022-06-27 17:29 UTC

**Comment by johnsonc-EsriCA** [comment] 2023-04-13 19:42
I am encountering the same issue.  Fresh install of Pro 3.1 and associated version of the deep learning libraries.  Trying to run "Detect Objects with Deep Learning" and Pro crashes out/shuts down almost right away.  I am wondering if it's because my CPU is AMD instead of Intel.  My specs:

OS: Windows 11
CPU: AMD Ryzen 7 3700X
RAM: 32GB
GPU: NVIDIA GeForce RTX 3060 Ti

Any advise would be appreciated!

**Comment by ecodynlab** [comment] 2023-04-21 14:17
Same problem here. Fresh install of ArGISPro 3.1 and dependencies. The application crashes the moment the .dlpk is specified. No dialog or crash dump in C:\Users\<username>\AppData\Local\ESRI\ErrorReports.

**Comment by johnsonc-EsriCA** [comment] 2023-04-21 16:22
@scdub, I've emailed your Esri Inc email with a couple of crash dump files (from my Esri Canada email).  Would you please confirm if you have received them?  Thanks for looking into this issue.

**Comment by scdub** [comment] 2023-04-25 03:35
@johnsonc-EsriCA Based on your crashdump, it looks like there is an invalid interaction with the Python GIL that is occurring causing the crash. Could you confirm you're using the building footprints USA DLPK? Could you try a couple of things to help isolate this issue? Could you see if it reproduces outside of the Pro application (e.g. running from standalone Python or a Notebook). Secondarily, could you see if temporarily removing data interoperability has any effect on the output?

**Comment by johnsonc-EsriCA** [comment] 2023-04-27 21:55
Any advice would be appreciated.

Thanks,

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>

From: Johnson Chan
Sent: April 25, 2023 10:31
To: Esri/deep-learning-frameworks ***@***.***>; Esri/deep-learning-frameworks ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Esri/deep-learning-frameworks] Downloaded everything but crashes my arcpro (Issue #46)

Hi Shaun,

Yes I am using the Building Footprints USA DLPK.  I did another test on an internal testing VM and it looks like I was able to load the model definition successfully:

***@***.***


The Pro here is 3.1.1 and has Data Interop installed as well.  So it appears something on my own machine is causing the invalidity with the Python GIL.

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>

**Comment by johnsonc-EsriCA** [comment] 2023-05-05 23:12
Good day,

Just would like to see if you’ve had time to take a further look at this issue.

Thanks!

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>

From: Johnson Chan
Sent: April 27, 2023 14:55
To: Esri/deep-learning-frameworks ***@***.***>; Esri/deep-learning-frameworks ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Esri/deep-learning-frameworks] Downloaded everything but crashes my arcpro (Issue #46)

Any advice would be appreciated.

Thanks,

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>

From: Johnson Chan
Sent: April 25, 2023 10:31
To: Esri/deep-learning-frameworks ***@***.******@***.***>>; Esri/deep-learning-frameworks ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [Esri/deep-learning-frameworks] Downloaded everything but crashes my arcpro (Issue #46)

Hi Shaun,

Yes I am using the Building Footprints USA DLPK.  I did another test on an internal testing VM and it looks like I was able to load the model definition successfully:

***@***.***


The Pro here is 3.1.1 and has Data Interop installed as well.  So it appears something on my own machine is causing the invalidity with the Python GIL.

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>

**Comment by scdub** [comment] 2023-05-05 23:17
@johnsonc-EsriCA I was able to look at the crash dumps, but unfortunately they don't contain enough information to isolate the cause of the issue. Could you help isolate causes by trying these things on the affected machine?

> Could you see if it reproduces outside of the Pro application (e.g. running from standalone Python or a Notebook). Secondarily, could you see if temporarily removing data interoperability has any effect on the output?

Thanks!
Shaun

**Comment by johnsonc-EsriCA** [comment] 2023-05-05 23:35
Hi Shaun,

Yes I am using the Building Footprints USA DLPK.  I did another test on an internal testing VM and it looks like I was able to load the model definition successfully:

***@***.***


The Pro here on the VM is 3.1.1 and has Data Interop installed as well.  So it appears something on my own machine is causing the invalidity with the Python GIL.  So I am trying to figure out what it is on my machine that is causing this.  I’ve tried other dlpks and they seem to load just fine without crashing on my machine.  To give more info, I do have the latest Python installed on my machine (3.11.3) and I am not sure if it is conflicting with the Python version that comes with Pro, although since the Pro version of Python is in a conda-based read-only environment, it shouldn’t matter.

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>


Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>

**Comment by scdub** [comment] 2023-05-05 23:38
I wouldn't expect an issue with a separate Python installation, especially of a different version. Could you try to reproduce the issue outside of the Pro application? I know its a pain, but separately it also is worth trying to temporarily uninstall DI to see if there is any effect, independently of it executing correctly on your other machine.

**Comment by johnsonc-EsriCA** [comment] 2023-05-19 15:18
Sounds good Shaun I can try to do it outside of my Pro for testing.  Do you happened to have a sample notebook/script that I can use to test run the Building Footprints USA model in Jypyter?

Thanks!

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>

**Comment by scdub** [comment] 2023-05-19 15:54
You can take one of the failed runs from the History pane, and export it to a Python command:

![image](https://github.com/Esri/deep-learning-frameworks/assets/46331011/bb9dc717-28d2-4702-8884-f5f998f24100)

From that, you can paste that command into a standalone Notebook or Python session and it should execute the same model analysis without Pro.

**Comment by johnsonc-EsriCA** [comment] 2023-05-19 15:57
Hi Shaun,

The problem is that when I tried to add in the dlpk into the Detect Objects tool, it crashed out of Pro.  So there was no failed run.

Thanks,

Johnson

Johnson Chan, MGIS | Technical Solutions Specialist
Esri Canada | 610-1130 West Pender | Vancouver BC V6E 4A4
T 604-695-7404 | M 236-330-7775 | esri.ca<https://esri.ca/> | LinkedIn<https://www.linkedin.com/in/johnson-chan-mgis-08b95a40>
