### ISSUE TITLE
Once installing with 3.0.3 Arcpro can't create a clone environment anymore

### ISSUE THREAD

**Issue by kpierce8** [Esri/deep-learning-frameworks#58] opened 2023-01-03 20:55 UTC
After successfully running the deep learning framework install on 3.0.3, Arcpro can't create clone environments anymore. The error text is placed here. Also the error text in the Arcpro dialogue doesn't have a copy option and "fades" away after about 2 seconds. It took many tries to capture the text quickly enough to save it to the attached document. On my read of it, it looked like an issue accepting a licenses agreement from NVIDIA as part of the downloads. 

[CondaCloneError.txt](https://github.com/Esri/deep-learning-frameworks/files/10339681/CondaCloneError.txt)

my work/ESRI customer email is kenneth.piercejr@dfw.wa.gov (separate from my github)

**Comment by scdub** [comment] 2023-01-11 15:59
@kpierce8 Unfortunately, I am familiar with the error you are receiving, it isn't directly linked with the DL installer, but is caused by the Jupyter stack wanting to modify global state which fails in strange ways. You can try again, see if it reproduces, most of the time it looks to be an intermittent issue. You can run Pro as an administrator and it will be able to write to the file. We have an issue logged for this, and will look to address it in a future release.

**Comment by KDeser** [comment] 2023-02-04 16:34
What's the likelihood that this will be resolved in ArcGIS Pro 3.1?

**Comment by scdub** [comment] 2023-02-07 04:45
The issue has been with us for a number of releases, will try to get it fixed soon and backported to 3.1, but its intermittent nature typically means retrying will work. If you just need a clone quickly, you can open a Python Command Prompt session and run `conda create -n pro-clone arcpy=3.0 python=3.9` and you'll get an environment which is the "base" ArcPy environment without the deep learning package set. You can then optionally install DL onto that by adding `deep-learning-essentials`, but typically if you aren't doing deep learning in all environments, keep DL just in a single one since each deep learning environment takes 10+GB of disk.

**Comment by LuisRguezEsriSpain** [comment] 2023-02-10 08:13
I solved this issue giving Full Control permissions for the directory "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3" to the windows user that execute the clone environment.

**Comment by scdub** [comment] 2023-06-14 16:50
This issue is BUG-000149939 and has been addressed in the next release of Pro. Until that is released, the workaround is to start Pro and immediately go to the backstage rather than opening a project which uses Python. The conflict specifically happens when Pro has already loaded Python components and the clone operation occurs.

**Closed by scdub** 2023-06-14 16:50 UTC
